### ISSUE TITLE
How temporary is the name?

### ISSUE THREAD

**Issue by woollyGibbon** [sdttttt/gcr#12]
Hi, your readme/about page mentions that grc is a temporary name. Is it likely to change in the near future? 

I am developing a new crate that I'd hoped to use the name grc for. I'm happy to change the name as it's still very much a work in progress but if this will be changing soon I'll leave it as it is.

Thanks and good luck with the project.

**Comment by sdttttt** [comment]
> Hi, your readme/about page mentions that grc is a temporary name. Is it likely to change in the near future?
> 
> I am developing a new crate that I'd hoped to use the name grc for. I'm happy to change the name as it's still very much a work in progress but if this will be changing soon I'll leave it as it is.
> 
> Thanks and good luck with the project.

I'm sorry, I don't have a better idea of names for the time being. The name GRC may be retained for a long time.🥺

**Comment by woollyGibbon** [comment]
No problem. I'll start thinking of alternatives.
