### ISSUE TITLE
Specify the configuration file with command line parameters.

### ISSUE THREAD

**Issue by sdttttt** [sdttttt/gcr#23]
Currently, GRC locks grc.toml as a configuration file.

**Comment by sdttttt** [comment]
目前, 我没有这个时间..

**Comment by KlausDevWalker** [comment]
Installing with **cargo** I didn't receive a **grc.toml**. Where do I have to put it for **gcr** notice it?
P.S: in the README you say that a semicolon separates the type from the description of the type. But the example right below shows an equal sign and an open bracket after that.

**Comment by sdttttt** [comment]
@KlausDevWalker , I thank you for using it. 

➢ Where do I have to put it for gcr notice it?

`grc.toml` needs to be in the **root** directory of the repo.


➢ in the README you say that a semicolon separates the type from the description of the type. But the example right below shows an equal sign and an open bracket after that.


This is my writing mistake. I'm sorry that my README has caused trouble with your understanding.


Subject: Re: [sdttttt/gcr] Specify the configuration file with command lineparameters. (#23)

Installing with cargo I didn't receive a grc.toml. Where do I have to put it for gcr notice it?
P.S: in the README you say that a semicolon separates the type from the description of the type. But the example right below shows an equal sign and an open bracket after that.

**Comment by KlausDevWalker** [comment]
Thanks for answering and for this great project :)

``grc.toml` needs to be in the **root** directory of the repo.`

What about the **cargo** install? That didn't come with this file.

**Comment by sdttttt** [comment]
> What about the **cargo** install? That didn't come with this file.

@KlausDevWalker, `cargo` is the Rust package manager. Just like `npm` of `node.js`. Information about `cargo` can be found [here](https://doc.rust-lang.org/cargo/index.html).  

Rust programmers usually install binary products produced by Rust in this way `cargo install grc`. Just like `npm install -g git-cz`.

For non-Rust users, I recommend downloading a binary package you like at [Release](https://github.com/sdttttt/gcr/releases).

P.S: If you are using `macos`, I have not built it in the workflows, you may need to download rustup to install grc. sorry  :(

**Comment by KlausDevWalker** [comment]
Sorry for your trouble. I meant that if I clone this repo, I get the `grc.toml`, but when I use `cargo`, don't.

**Comment by sdttttt** [comment]
> Sorry for your trouble. I meant that if I clone this repo, I get the `grc.toml`, but when I use `cargo`, don't.

@KlausDevWalker , Oh, sorry, my en is not good.

Here's the thing. When `grc` executes, it will check whether `grc.toml`. exists in the repo root directory of the current repo. Each repo needs to have a `grc.toml` in the repo root directory. 

If you need a `grc.toml` with **default global configuration**, please come up with an **issue**, and I will take care of it :)

**Comment by KlausDevWalker** [comment]
You're English is way better than mine. Thanks for the reply. I'll create a issue as you suggested. :)
