### ISSUE TITLE
env GIT_AUTHOR_NAME is not used

### ISSUE THREAD

**Issue by laggardkernel** [sdttttt/gcr#30]
I use `direnv` to export env `GIT_AUTHOR_NAME`, `GIT_AUTHOR_EMAIL` ... in specific directory to change author and committer. Seems these environment variables are not used.

**Comment by sdttttt** [comment]
Thank you for your question. I'll fix them as soon as possible :)

**Comment by sdttttt** [comment]
This question was improved in #33

**Comment by laggardkernel** [comment]
Maybe you've misunderstood me. The environment variables `GIT_AUTHOR_NAME`, `GIT_AUTHOR_EMAIL`, `GIT_COMMITTER_NAME`, `GIT_COMMITTER_EMAIL` take precedence over the committer and author in config file `$XDG_CONFIG_HOME/git/config` or `.gitconfig`.

There're others shell env vars used by `git`. Check [10.8 Git Internals - Environment Variables](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables) for detail.

I suppose `grc` build an interface to help users compose the commit message, then call the `git` command and pass the commit message to it. I mean I suppose the `grc` works as a **wrapper** for command `git`. And when the `git` command is called, shell environment variable should be inherited from the parent process `grc`, which is also supposed to inherited env vars from the outside shell where users call `grc`.

It seems I was wrong about how `grc` works?

**Comment by sdttttt** [comment]
> Maybe you've misunderstood me. The environment variables `GIT_AUTHOR_NAME`, `GIT_AUTHOR_EMAIL`, `GIT_COMMITTER_NAME`, `GIT_COMMITTER_EMAIL` take precedence over the committer and author in config file `$XDG_CONFIG_HOME/git/config` or `.gitconfig`.
> 
> There're others shell env vars used by `git`. Check [10.8 Git Internals - Environment Variables](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables) for detail.
> 
> I suppose `grc` build an interface to help users compose the commit message, then call the `git` command and pass the commit message to it. I mean I suppose the `grc` works as a **wrapper** for command `git`. And when the `git` command is called, shell environment variable should be inherited from the parent process `grc`, which is also supposed to inherited env vars from the outside shell where users call `grc`.
> 
> It seems I was wrong about how `grc` works?

Oh, I'm sorry, I rarely use environment variables to modify some of the actions of git. I don't know about that.
I will consider modifying them in the next release.
