### ISSUE TITLE
[Bug Report] 1st commit after git init failed

### ISSUE THREAD

**Issue by laggardkernel** [sdttttt/gcr#44]
Steps to reproduce

1. git init
2. touch `README.md`, `git add README.md`
3. `grc`, then failed

```
❯ grc
✔ Which scope? (Optional) ·
✔ Commit Message ? · 1st commit
✔ Provide a longer description? (Optional) ·
✔ PR & Issues this commit closes, e.g 123: (Optional) ·
GRC: feat: 1st commit
GRC: reference 'refs/heads/master' not found

```

Environments

- grc version: v1.0.0 from release page. `grc --version` GRC 1..0.0.beta.1
- git version: 2.30.1
- OS: macOS 10.14.6

**Comment by sdttttt** [comment]
Oh, This bug does exist in **all** versions of GRC and I may have forgotten about it. It has to do with GRC's behavior of looking for HEAD.

GRC finds the `HEAD` of the current branch through previous commit records. For the repo without commit records, GRC will not be able to find the `HEAD`. I will try to fix it at the next version.

For now, If to avoid this problem, need to use GRC on the branch of the **non-empty** commit record.

Thanks your issue, @laggardkernel
