### ISSUE TITLE
I package it on AUR

### ISSUE THREAD

**Issue by CoelacanthusHex** [sdttttt/gcr#48]
link is https://aur.archlinux.org/packages/git-grc/

**Comment by CoelacanthusHex** [comment]
and you can add a tip in README like this https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=git-grc#n34

```bash
ln -sf /usr/bin/grc /usr/bin/git-grc
```

so user can use git subcommand `git grc` instead of `grc` or `git commit`

**Comment by sdttttt** [comment]
Hi, @CoelacanthusHex, thank you for everything.

But I'm not a user of Arch Linux. 
The versions on other platforms are hard for me to maintain.


发件人: Coelacanthus
发送时间: 2021年3月16日 12:27
收件人: sdttttt/gcr
抄送: Subscribed
主题: [sdttttt/gcr] I package it on AUR (#48)

link is https://aur.archlinux.org/packages/git-grc/
