### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by Easonzero** [sdttttt/gcr#63]
encounter an error when i run `cargo install grc`
```text
error: failed to compile `grc v1.2.0`, intermediate artifacts can be found at `/tmp/cargo-installBHdw34`

Caused by:
  failed to select a version for the requirement `zeroize = "^0.9.3"`
  candidate versions found which didn't match: 1.3.0, 1.2.0, 1.1.1, ...
  location searched: crates.io index
  required by package `dialoguer v0.7.1`
      ... which is depended on by `grc v1.2.0`
```

**Comment by qixiaoo** [comment]
The crate zeroize v0.9.3 that dialoguer v0.7.1 depends on has been yanked. Perhaps we can upgrade dialoguer to latest version to solve this problem.

**Comment by sdttttt** [comment]
It looks like `zeroize` has **yank** all versions before 1.0.0 on crates.io.

In the next version, I will update Dialoguer to solve this problem.

**Comment by sdttttt** [comment]
@Easonzero, Waiting so long.. GRC has been updated to `1.2.1`. Now `cargo` should work normally.

I have been busy recently, so I didn't pay much attention to GRC, sorry.
