### ISSUE TITLE
Pre-hooks may change the tracked files, but not commit changes

### ISSUE THREAD

**Issue by Forsworns** [sdttttt/gcr#77]
Hi, the pre-hooks may change the tracked files, while the gcr won't track these changes. 

For example, when `cargo fmt` is hooked, I observe these: 

![image](https://user-images.githubusercontent.com/24567080/143003017-f0e459c0-86b0-4a9c-8bee-97205e5185c8.png)

![image](https://user-images.githubusercontent.com/24567080/143003096-fed4bf73-a08b-4352-8854-a84e7ab732b5.png)

Here is the configuration:
```
emoji = true
pre = ["cargo fmt"]
after = []
```

**Comment by sdttttt** [comment]
Hi! @Forsworns, tk for u issue! This problem is really caused by me. I am busy recently. I will fix them as soon as possible if I have time.

**Comment by Forsworns** [comment]
In fact, I tried to fix it this afternoon :) Maybe you can review it when you have time. The idea is to postpone the `add_files()` in `pre_commit()` after pre-hooks. And if the `config.command_mode()` is `Mode::Commit`, only changes in tracked files would be recorded.
